### ISSUE TITLE
Scroll seems to be broken

### ISSUE THREAD

**Issue by taichouvik** [Aaron-Paul/Aaron-Paul#1]
<img width="1536" alt="image" src="https://github.com/Aaron-Paul/Aaron-Paul/assets/19325877/6356f11c-906c-4fc0-a0d3-c577c17c18d0">

**Comment by Aaron-Paul** [comment]
https://stackoverflow.com/questions/68034622/chrome-bug-infinite-scrolling-above-page-body-several-pages

existing issue in chromium based browers ,but for your happiness i have added a temporary fix to prevent infinite scroll 
but it makes the website slow on chromium browsers 
![Uploading Screenshot 2024-05-08 at 9.46.07 PM.png…]()

**Comment by Aaron-Paul** [comment]
resetting to default scroll 

to remove infinite scroll in chrome and edge
 html{
    height: 100%;
    overflow: hidden;
}
body{
    height: 100%;
    overflow: auto;
    overscroll-behavior: none;
}
